services:
  webserver:
    image: nginx:alpine
    container_name: express-webserver
    ports:
      - "80:443"
    volumes:
      - ./:/var/www/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  app: 
    container_name: express-app
    build: 
      context: .
      target: setup
    
